---

- name: "{{ kafka_mode }} | init temp vars for {{ item.name }} config (1/3)"
  ansible.builtin.set_fact:
    __string_properties: ""
    __properties: {}

- name: "{{ kafka_mode }} | init temp vars for {{ item.name }} config (2/3)"
  ansible.builtin.set_fact:
    __properties: "{{ __properties | combine({property.key: property.value}) }}"
  when: property.key not in ['name']
  loop: "{{ item | dict2items }}"
  loop_control:
    loop_var: property

- name: "{{ kafka_mode }} | init temp vars for {{ item.name }} config (3/3)"
  ansible.builtin.set_fact:
    __string_properties: "{{ __string_properties }}{{ (id > 0) | ternary(',', '') }}{{ conf.key }}={{ conf.value }}"
  loop: "{{ __properties | dict2items }}"
  loop_control:
    index_var: id
    loop_var: conf

- name: "{{ kafka_mode }} | obtain config for topic"
  become: true
  become_user: "{{ kafka_user_owner_service }}"
  become_method: machinectl
  become_exe: "sudo machinectl"
  ansible.builtin.command: "{{ kafka_install_dir }}/bin/kafka-topics.sh --bootstrap-server {{ kafka_bootstrap_server }} --topic {{ item.name }} --describe"
  register: __kafka_topics_config_described_full
  changed_when: false

- name: "{{ kafka_mode }} | topics to alter"
  ansible.builtin.set_fact:
    __kafka_topics_config_to_alter: "{{ __kafka_topics_config_described_full.stdout | replace('Configs for topic ' + item.name + ' are ', '') }}"

- name: "{{ kafka_mode }} | configure kafka topics"
  become: true
  become_user: "{{ kafka_user_owner_service }}"
  become_method: machinectl
  become_exe: "sudo machinectl"
  ansible.builtin.command: "{{ kafka_install_dir }}/bin/kafka-configs.sh --bootstrap-server {{ kafka_bootstrap_server }} --alter --entity-type topics --entity-name {{ item.name }} --add-config {{ __string_properties }}"
  when: __kafka_topics_config_to_alter | trim  != __string_properties
  changed_when: false
